### ISSUE TITLE
咨询，可以运行在web页面吗？

### ISSUE THREAD

**Issue by luckrill** [zhaipro/plane#1]
现在web页面刚方便，所以问问

**Comment by zhaipro** [comment]
我对web页的了解几乎为零。刚刚入手该项目，目标是融入体感游戏。

**Comment by luckrill** [comment]
web的游戏，应该基于JS
python游戏，应该在桌面版
希望我有空推出 桌面版工具软件，之后可以推送开源游戏让用户玩玩
用python写一个桌面版软件，之后推送、集成 各种好的应用，直接让最终用户体验

**Comment by luckrill** [comment]
关闭这个issue吧，今天拜读了您的若干项目，有些收获

**Comment by zhaipro** [comment]
玩的开心就好
